import "wbl/styles/globals.css";

import { type Metadata, type Viewport } from "next";
import { Geist } from "next/font/google";

import { BottomBar } from "wbl/app/_components/BottomBar";
import { Header } from "wbl/app/_components/Header";
import { getSession } from "wbl/server/better-auth/server";

import { TRPCReactProvider } from "wbl/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const viewport: Viewport = {
  viewportFit: "cover",
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getSession();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-surface min-h-dvh pb-[calc(4rem+env(safe-area-inset-bottom))] text-white md:pb-0">
        <Header initialUserName={session?.user.name} />
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <BottomBar />
      </body>
    </html>
  );
}
